// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Spacelift
{
    public static class GetBitbucketDatacenterIntegration
    {
        /// <summary>
        /// `spacelift.getBitbucketDatacenterIntegration` returns details about Bitbucket Datacenter integration
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Spacelift = Pulumi.Spacelift;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var bitbucketDatacenterIntegration = Output.Create(Spacelift.GetBitbucketDatacenterIntegration.InvokeAsync());
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetBitbucketDatacenterIntegrationResult> InvokeAsync(InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetBitbucketDatacenterIntegrationResult>("spacelift:index/getBitbucketDatacenterIntegration:getBitbucketDatacenterIntegration", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetBitbucketDatacenterIntegrationResult
    {
        public readonly string ApiHost;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string UserFacingHost;
        public readonly string WebhookSecret;

        [OutputConstructor]
        private GetBitbucketDatacenterIntegrationResult(
            string apiHost,

            string id,

            string userFacingHost,

            string webhookSecret)
        {
            ApiHost = apiHost;
            Id = id;
            UserFacingHost = userFacingHost;
            WebhookSecret = webhookSecret;
        }
    }
}
