// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Spacelift
{
    public static class GetCurrentStack
    {
        /// <summary>
        /// `spacelift.getCurrentStack` is a data source that provides information about the current administrative stack if the run is executed within Spacelift by a stack or module. This allows clever tricks like attaching contexts or policies to the stack that manages them.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Spacelift = Pulumi.Spacelift;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var @this = Output.Create(Spacelift.GetCurrentStack.InvokeAsync());
        ///         var core_kubeconfig = new Spacelift.EnvironmentVariable("core-kubeconfig", new Spacelift.EnvironmentVariableArgs
        ///         {
        ///             StackId = @this.Apply(@this =&gt; @this.Id),
        ///             Name = "CHUNKY",
        ///             Value = "bacon",
        ///         });
        ///     }
        /// 
        /// }
        /// ```
        /// 
        /// &lt;!-- schema generated by tfplugindocs --&gt;
        /// {{% /example %}}
        /// {{% /examples %}}
        /// ## Schema
        /// 
        /// ### Optional
        /// 
        /// - **id** (String) The ID of this resource.
        /// </summary>
        public static Task<GetCurrentStackResult> InvokeAsync(InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetCurrentStackResult>("spacelift:index/getCurrentStack:getCurrentStack", InvokeArgs.Empty, options.WithVersion());
    }


    [OutputType]
    public sealed class GetCurrentStackResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetCurrentStackResult(string id)
        {
            Id = id;
        }
    }
}
