// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Spacelift
{
    public static class GetVcsAgentPools
    {
        /// <summary>
        /// `spacelift.getVcsAgentPools` represents the VCS agent pools assigned to the Spacelift account.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Spacelift = Pulumi.Spacelift;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var vcs_agent_pools = Spacelift.GetVcsAgentPools.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetVcsAgentPoolsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetVcsAgentPoolsResult>("spacelift:index/getVcsAgentPools:getVcsAgentPools", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// `spacelift.getVcsAgentPools` represents the VCS agent pools assigned to the Spacelift account.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Spacelift = Pulumi.Spacelift;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var vcs_agent_pools = Spacelift.GetVcsAgentPools.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetVcsAgentPoolsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetVcsAgentPoolsResult>("spacelift:index/getVcsAgentPools:getVcsAgentPools", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// `spacelift.getVcsAgentPools` represents the VCS agent pools assigned to the Spacelift account.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Spacelift = Pulumi.Spacelift;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var vcs_agent_pools = Spacelift.GetVcsAgentPools.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetVcsAgentPoolsResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetVcsAgentPoolsResult>("spacelift:index/getVcsAgentPools:getVcsAgentPools", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetVcsAgentPoolsResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetVcsAgentPoolsVcsAgentPoolResult> VcsAgentPools;

        [OutputConstructor]
        private GetVcsAgentPoolsResult(
            string id,

            ImmutableArray<Outputs.GetVcsAgentPoolsVcsAgentPoolResult> vcsAgentPools)
        {
            Id = id;
            VcsAgentPools = vcsAgentPools;
        }
    }
}
