// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Spacelift
{
    /// <summary>
    /// `spacelift.SecurityEmail` represents an email address that receives notifications about security issues in Spacelift.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Spacelift = Pulumi.Spacelift;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Spacelift.SecurityEmail("example", new()
    ///     {
    ///         Email = "user@example.com",
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [SpaceliftResourceType("spacelift:index/securityEmail:SecurityEmail")]
    public partial class SecurityEmail : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Email address to which the security notifications are sent
        /// </summary>
        [Output("email")]
        public Output<string> Email { get; private set; } = null!;


        /// <summary>
        /// Create a SecurityEmail resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SecurityEmail(string name, SecurityEmailArgs args, CustomResourceOptions? options = null)
            : base("spacelift:index/securityEmail:SecurityEmail", name, args ?? new SecurityEmailArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SecurityEmail(string name, Input<string> id, SecurityEmailState? state = null, CustomResourceOptions? options = null)
            : base("spacelift:index/securityEmail:SecurityEmail", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://downloads.spacelift.io/pulumi-plugins",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SecurityEmail resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SecurityEmail Get(string name, Input<string> id, SecurityEmailState? state = null, CustomResourceOptions? options = null)
        {
            return new SecurityEmail(name, id, state, options);
        }
    }

    public sealed class SecurityEmailArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Email address to which the security notifications are sent
        /// </summary>
        [Input("email", required: true)]
        public Input<string> Email { get; set; } = null!;

        public SecurityEmailArgs()
        {
        }
        public static new SecurityEmailArgs Empty => new SecurityEmailArgs();
    }

    public sealed class SecurityEmailState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Email address to which the security notifications are sent
        /// </summary>
        [Input("email")]
        public Input<string>? Email { get; set; }

        public SecurityEmailState()
        {
        }
        public static new SecurityEmailState Empty => new SecurityEmailState();
    }
}
