// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Spacelift
{
    /// <summary>
    /// `spacelift.StackActivator` is used to to enable/disable Spacelift Stack.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Spacelift = Pulumi.Spacelift;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var app = new Spacelift.Stack("app", new()
    ///     {
    ///         Branch = "master",
    ///         Repository = "app",
    ///     });
    /// 
    ///     var test = new Spacelift.StackActivator("test", new()
    ///     {
    ///         Enabled = true,
    ///         StackId = app.Id,
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [SpaceliftResourceType("spacelift:index/stackActivator:StackActivator")]
    public partial class StackActivator : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Enable/disable stack
        /// </summary>
        [Output("enabled")]
        public Output<bool> Enabled { get; private set; } = null!;

        /// <summary>
        /// ID of the stack to enable/disable
        /// </summary>
        [Output("stackId")]
        public Output<string> StackId { get; private set; } = null!;


        /// <summary>
        /// Create a StackActivator resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public StackActivator(string name, StackActivatorArgs args, CustomResourceOptions? options = null)
            : base("spacelift:index/stackActivator:StackActivator", name, args ?? new StackActivatorArgs(), MakeResourceOptions(options, ""))
        {
        }

        private StackActivator(string name, Input<string> id, StackActivatorState? state = null, CustomResourceOptions? options = null)
            : base("spacelift:index/stackActivator:StackActivator", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://downloads.spacelift.io/pulumi-plugins",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing StackActivator resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static StackActivator Get(string name, Input<string> id, StackActivatorState? state = null, CustomResourceOptions? options = null)
        {
            return new StackActivator(name, id, state, options);
        }
    }

    public sealed class StackActivatorArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enable/disable stack
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        /// <summary>
        /// ID of the stack to enable/disable
        /// </summary>
        [Input("stackId", required: true)]
        public Input<string> StackId { get; set; } = null!;

        public StackActivatorArgs()
        {
        }
        public static new StackActivatorArgs Empty => new StackActivatorArgs();
    }

    public sealed class StackActivatorState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enable/disable stack
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// ID of the stack to enable/disable
        /// </summary>
        [Input("stackId")]
        public Input<string>? StackId { get; set; }

        public StackActivatorState()
        {
        }
        public static new StackActivatorState Empty => new StackActivatorState();
    }
}
