# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'GetBitbucketCloudIntegrationResult',
    'AwaitableGetBitbucketCloudIntegrationResult',
    'get_bitbucket_cloud_integration',
]

@pulumi.output_type
class GetBitbucketCloudIntegrationResult:
    """
    A collection of values returned by getBitbucketCloudIntegration.
    """
    def __init__(__self__, id=None, username=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if username and not isinstance(username, str):
            raise TypeError("Expected argument 'username' to be a str")
        pulumi.set(__self__, "username", username)

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def username(self) -> str:
        """
        Bitbucket Cloud username
        """
        return pulumi.get(self, "username")


class AwaitableGetBitbucketCloudIntegrationResult(GetBitbucketCloudIntegrationResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetBitbucketCloudIntegrationResult(
            id=self.id,
            username=self.username)


def get_bitbucket_cloud_integration(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetBitbucketCloudIntegrationResult:
    """
    `get_bitbucket_cloud_integration` returns details about Bitbucket Cloud integration

    ## Example Usage

    ```python
    import pulumi
    import pulumi_spacelift as spacelift

    bitbucket_cloud_integration = spacelift.get_bitbucket_cloud_integration()
    ```
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('spacelift:index/getBitbucketCloudIntegration:getBitbucketCloudIntegration', __args__, opts=opts, typ=GetBitbucketCloudIntegrationResult).value

    return AwaitableGetBitbucketCloudIntegrationResult(
        id=__ret__.id,
        username=__ret__.username)
