# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['StackActivatorArgs', 'StackActivator']

@pulumi.input_type
class StackActivatorArgs:
    def __init__(__self__, *,
                 enabled: pulumi.Input[bool],
                 stack_id: pulumi.Input[str]):
        """
        The set of arguments for constructing a StackActivator resource.
        :param pulumi.Input[bool] enabled: Enable/disable stack
        :param pulumi.Input[str] stack_id: ID of the stack to enable/disable
        """
        pulumi.set(__self__, "enabled", enabled)
        pulumi.set(__self__, "stack_id", stack_id)

    @property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[bool]:
        """
        Enable/disable stack
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[bool]):
        pulumi.set(self, "enabled", value)

    @property
    @pulumi.getter(name="stackId")
    def stack_id(self) -> pulumi.Input[str]:
        """
        ID of the stack to enable/disable
        """
        return pulumi.get(self, "stack_id")

    @stack_id.setter
    def stack_id(self, value: pulumi.Input[str]):
        pulumi.set(self, "stack_id", value)


@pulumi.input_type
class _StackActivatorState:
    def __init__(__self__, *,
                 enabled: Optional[pulumi.Input[bool]] = None,
                 stack_id: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering StackActivator resources.
        :param pulumi.Input[bool] enabled: Enable/disable stack
        :param pulumi.Input[str] stack_id: ID of the stack to enable/disable
        """
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if stack_id is not None:
            pulumi.set(__self__, "stack_id", stack_id)

    @property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[bool]]:
        """
        Enable/disable stack
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "enabled", value)

    @property
    @pulumi.getter(name="stackId")
    def stack_id(self) -> Optional[pulumi.Input[str]]:
        """
        ID of the stack to enable/disable
        """
        return pulumi.get(self, "stack_id")

    @stack_id.setter
    def stack_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "stack_id", value)


class StackActivator(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 enabled: Optional[pulumi.Input[bool]] = None,
                 stack_id: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        `StackActivator` is used to to enable/disable Spacelift Stack.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_spacelift as spacelift

        app = spacelift.Stack("app",
            branch="master",
            repository="app")
        test = spacelift.StackActivator("test",
            enabled=True,
            stack_id=app.id)
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[bool] enabled: Enable/disable stack
        :param pulumi.Input[str] stack_id: ID of the stack to enable/disable
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: StackActivatorArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        `StackActivator` is used to to enable/disable Spacelift Stack.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_spacelift as spacelift

        app = spacelift.Stack("app",
            branch="master",
            repository="app")
        test = spacelift.StackActivator("test",
            enabled=True,
            stack_id=app.id)
        ```

        :param str resource_name: The name of the resource.
        :param StackActivatorArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(StackActivatorArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 enabled: Optional[pulumi.Input[bool]] = None,
                 stack_id: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = StackActivatorArgs.__new__(StackActivatorArgs)

            if enabled is None and not opts.urn:
                raise TypeError("Missing required property 'enabled'")
            __props__.__dict__["enabled"] = enabled
            if stack_id is None and not opts.urn:
                raise TypeError("Missing required property 'stack_id'")
            __props__.__dict__["stack_id"] = stack_id
        super(StackActivator, __self__).__init__(
            'spacelift:index/stackActivator:StackActivator',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            enabled: Optional[pulumi.Input[bool]] = None,
            stack_id: Optional[pulumi.Input[str]] = None) -> 'StackActivator':
        """
        Get an existing StackActivator resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[bool] enabled: Enable/disable stack
        :param pulumi.Input[str] stack_id: ID of the stack to enable/disable
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _StackActivatorState.__new__(_StackActivatorState)

        __props__.__dict__["enabled"] = enabled
        __props__.__dict__["stack_id"] = stack_id
        return StackActivator(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[bool]:
        """
        Enable/disable stack
        """
        return pulumi.get(self, "enabled")

    @property
    @pulumi.getter(name="stackId")
    def stack_id(self) -> pulumi.Output[str]:
        """
        ID of the stack to enable/disable
        """
        return pulumi.get(self, "stack_id")

