// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Spacelift.Outputs
{

    [OutputType]
    public sealed class GetPoliciesPolicyResult
    {
        /// <summary>
        /// ID of the policy
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<string> Labels;
        /// <summary>
        /// Name of the policy
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// ID (slug) of the space the policy is in
        /// </summary>
        public readonly string SpaceId;
        /// <summary>
        /// Type of the policy
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private GetPoliciesPolicyResult(
            string id,

            ImmutableArray<string> labels,

            string name,

            string spaceId,

            string type)
        {
            Id = id;
            Labels = labels;
            Name = name;
            SpaceId = spaceId;
            Type = type;
        }
    }
}
