// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Spacelift.Outputs
{

    [OutputType]
    public sealed class GetStackKuberneteResult
    {
        /// <summary>
        /// Kubectl version.
        /// </summary>
        public readonly string KubectlVersion;
        /// <summary>
        /// Namespace of the Kubernetes cluster to run commands on. Leave empty for multi-namespace Stacks.
        /// </summary>
        public readonly string Namespace;

        [OutputConstructor]
        private GetStackKuberneteResult(
            string kubectlVersion,

            string @namespace)
        {
            KubectlVersion = kubectlVersion;
            Namespace = @namespace;
        }
    }
}
