# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

apiKeyEndpoint: Optional[str]
"""
Endpoint to use when authenticating with an API key outside of Spacelift
"""

apiKeyId: Optional[str]
"""
ID of the API key to use when executing outside of Spacelift
"""

apiKeySecret: Optional[str]
"""
API key secret to use when executing outside of Spacelift
"""

apiToken: Optional[str]
"""
Spacelift token generated by a run, only useful from within Spacelift
"""

