// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package spacelift

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

// `getCurrentStack` is a data source that provides information about the current administrative stack if the run is executed within Spacelift by a stack or module. This allows clever tricks like attaching contexts or policies to the stack that manages them.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
// 	"github.com/spacelift-io/spacelift-spacelift/sdk/go/spacelift/"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		this, err := spacelift.GetCurrentStack(ctx, nil, nil)
// 		if err != nil {
// 			return err
// 		}
// 		_, err = spacelift.NewEnvironmentVariable(ctx, "core_kubeconfig", &spacelift.EnvironmentVariableArgs{
// 			StackId: pulumi.String(this.Id),
// 			Name:    pulumi.String("CHUNKY"),
// 			Value:   pulumi.String("bacon"),
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
//
// <!-- schema generated by tfplugindocs -->
// ## Schema
//
// ### Optional
//
// - **id** (String) The ID of this resource.
func GetCurrentStack(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetCurrentStackResult, error) {
	var rv GetCurrentStackResult
	err := ctx.Invoke("spacelift:index/getCurrentStack:getCurrentStack", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getCurrentStack.
type GetCurrentStackResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
}
