// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package spacelift

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

// `ContextAttachment` represents a Spacelift attachment of a single context to a single stack or module, with a predefined priority.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-spacelift/sdk/go/spacelift"
// 	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
// 	"github.com/spacelift-io/spacelift-spacelift/sdk/go/spacelift/"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		opt0 := "apps-cluster"
// 		_, err := spacelift.LookupContextAttachment(ctx, &spacelift.LookupContextAttachmentArgs{
// 			ContextId: "prod-k8s-ie",
// 			StackId:   &opt0,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		opt1 := "terraform-aws-kafka"
// 		_, err = spacelift.LookupContextAttachment(ctx, &spacelift.LookupContextAttachmentArgs{
// 			ContextId: "prod-k8s-ie",
// 			ModuleId:  &opt1,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
//
// <!-- schema generated by tfplugindocs -->
// ## Schema
//
// ### Required
//
// - **context_id** (String) ID of the attached context
//
// ### Optional
//
// - **id** (String) The ID of this resource.
// - **module_id** (String) ID of the attached module
// - **stack_id** (String) ID of the attached stack
//
// ### Read-Only
//
// - **priority** (Number) priority of the context attachment, used in case of conflicts
func LookupContextAttachment(ctx *pulumi.Context, args *LookupContextAttachmentArgs, opts ...pulumi.InvokeOption) (*LookupContextAttachmentResult, error) {
	var rv LookupContextAttachmentResult
	err := ctx.Invoke("spacelift:index/getContextAttachment:getContextAttachment", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getContextAttachment.
type LookupContextAttachmentArgs struct {
	ContextId string  `pulumi:"contextId"`
	ModuleId  *string `pulumi:"moduleId"`
	StackId   *string `pulumi:"stackId"`
}

// A collection of values returned by getContextAttachment.
type LookupContextAttachmentResult struct {
	ContextId string `pulumi:"contextId"`
	// The provider-assigned unique ID for this managed resource.
	Id       string  `pulumi:"id"`
	ModuleId *string `pulumi:"moduleId"`
	Priority int     `pulumi:"priority"`
	StackId  *string `pulumi:"stackId"`
}
