// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package spacelift

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
	"github.com/spacelift-io/pulumi-spacelift/sdk/v2/go/spacelift/internal"
)

// `getIPs` returns the list of Spacelift's outgoing IP addresses, which you can use to whitelist connections coming from the Spacelift's "mothership". **NOTE:** this does not include the IP addresses of the workers in Spacelift's public worker pool. If you need to ensure that requests made during runs originate from a known set of IP addresses, please consider setting up a [private worker pool](https://docs.spacelift.io/concepts/worker-pools).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/spacelift-io/pulumi-spacelift/sdk/v2/go/spacelift"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := spacelift.GetIPs(ctx, nil, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetIPs(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetIPsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetIPsResult
	err := ctx.Invoke("spacelift:index/getIPs:getIPs", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getIPs.
type GetIPsResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// the list of spacelift.io outgoing IP addresses
	Ips []string `pulumi:"ips"`
}

func GetIPsOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetIPsResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetIPsResult, error) {
		r, err := GetIPs(ctx, opts...)
		var s GetIPsResult
		if r != nil {
			s = *r
		}
		return s, err
	}).(GetIPsResultOutput)
}

// A collection of values returned by getIPs.
type GetIPsResultOutput struct{ *pulumi.OutputState }

func (GetIPsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetIPsResult)(nil)).Elem()
}

func (o GetIPsResultOutput) ToGetIPsResultOutput() GetIPsResultOutput {
	return o
}

func (o GetIPsResultOutput) ToGetIPsResultOutputWithContext(ctx context.Context) GetIPsResultOutput {
	return o
}

func (o GetIPsResultOutput) ToOutput(ctx context.Context) pulumix.Output[GetIPsResult] {
	return pulumix.Output[GetIPsResult]{
		OutputState: o.OutputState,
	}
}

// The provider-assigned unique ID for this managed resource.
func (o GetIPsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetIPsResult) string { return v.Id }).(pulumi.StringOutput)
}

// the list of spacelift.io outgoing IP addresses
func (o GetIPsResultOutput) Ips() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetIPsResult) []string { return v.Ips }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetIPsResultOutput{})
}
