// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package spacelift

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupStack(ctx *pulumi.Context, args *LookupStackArgs, opts ...pulumi.InvokeOption) (*LookupStackResult, error) {
	var rv LookupStackResult
	err := ctx.Invoke("spacelift:index/getStack:getStack", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getStack.
type LookupStackArgs struct {
	StackId string `pulumi:"stackId"`
}

// A collection of values returned by getStack.
type LookupStackResult struct {
	Administrative               bool                     `pulumi:"administrative"`
	Autodeploy                   bool                     `pulumi:"autodeploy"`
	Autoretry                    bool                     `pulumi:"autoretry"`
	AwsAssumeRolePolicyStatement string                   `pulumi:"awsAssumeRolePolicyStatement"`
	BeforeInits                  []string                 `pulumi:"beforeInits"`
	Branch                       string                   `pulumi:"branch"`
	Cloudformations              []GetStackCloudformation `pulumi:"cloudformations"`
	Description                  string                   `pulumi:"description"`
	Gitlabs                      []GetStackGitlab         `pulumi:"gitlabs"`
	// The provider-assigned unique ID for this managed resource.
	Id                 string           `pulumi:"id"`
	Labels             []string         `pulumi:"labels"`
	ManageState        bool             `pulumi:"manageState"`
	Name               string           `pulumi:"name"`
	ProjectRoot        string           `pulumi:"projectRoot"`
	Pulumis            []GetStackPulumi `pulumi:"pulumis"`
	Repository         string           `pulumi:"repository"`
	RunnerImage        string           `pulumi:"runnerImage"`
	StackId            string           `pulumi:"stackId"`
	TerraformVersion   string           `pulumi:"terraformVersion"`
	TerraformWorkspace string           `pulumi:"terraformWorkspace"`
	WorkerPoolId       string           `pulumi:"workerPoolId"`
}
