// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Spacelift.Inputs
{

    public sealed class ModuleAzureDevopsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ID of the Azure Devops integration. If not specified, the default integration will be used.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// Indicates whether this is the default Azure DevOps integration
        /// </summary>
        [Input("isDefault")]
        public Input<bool>? IsDefault { get; set; }

        /// <summary>
        /// The name of the Azure DevOps project
        /// </summary>
        [Input("project", required: true)]
        public Input<string> Project { get; set; } = null!;

        public ModuleAzureDevopsArgs()
        {
        }
        public static new ModuleAzureDevopsArgs Empty => new ModuleAzureDevopsArgs();
    }
}
