// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Spacelift.Inputs
{

    public sealed class StackKubernetesArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Kubectl version.
        /// </summary>
        [Input("kubectlVersion")]
        public Input<string>? KubectlVersion { get; set; }

        /// <summary>
        /// Namespace of the Kubernetes cluster to run commands on. Leave empty for multi-namespace Stacks.
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        public StackKubernetesArgs()
        {
        }
        public static new StackKubernetesArgs Empty => new StackKubernetesArgs();
    }
}
