name: Build provider

on: { pull_request: {} }

concurrency:
  group: build-provider-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-provider:
    name: 👷‍♀️ Build provider
    runs-on: ubuntu-latest
    container: golang:1.21-alpine
    steps:
      - name: Install build dependencies
        run: apk add --no-cache alpine-sdk git bash

      - name: Check out repository code
        uses: actions/checkout@main
        with: { fetch-depth: 0 }

      - name: Treat repo as safe
        run: git config --global --add safe.directory /__w/pulumi-spacelift/pulumi-spacelift

      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: pulumi/pulumictl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pulumi
        uses: pulumi/actions@v4

      - name: Tag version
        run: |
          CURRENTTAG=$(git describe --tags --abbrev=0)
          git tag $CURRENTTAG${{ github.run_number }}

      - name: Print version
        run: pulumictl get version

      - name: Build provider
        run: make provider
        env:
          PROVIDER_OS: ${{ matrix.provider_os }}
