name: Library deployment

on:
  push:
    tags:
      - v*.*.*

jobs:
  preprod-provider-deployment:
    name: Build and upload provider
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@master
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.1.0
        with:
          repo: pulumi/pulumictl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
          registry-url: https://registry.npmjs.org
      - name: Install yarn
        run: npm install --global yarn
      - name: Setup DotNet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Setup DotNet ICU
        run: sudo apt-get update && sudo apt-get install -y icu-devtools
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Print version
        run: pulumictl get version
      # - name: Build provider
      #   run: make build_sdks
      #   env:
      #     PROVIDER_OS: linux
#      - name: Create .npmrc
#        run: echo "@spacelift-io:registry=https://npm.pkg.github.com
#  //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > sdk/nodejs/bin/.npmrc
#      - name: Create .npmrc
#        run: echo "@spacelift-io:registry=https://npm.pkg.github.com
#        //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
      - name: Create .npmrc
        run: echo "registry=https://npm.pkg.github.com/spacelift-io" > sdk/nodejs/bin/.npmrc
      - name: Publish npm package.
        run: cd sdk/nodejs/bin && npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
