name: Library deployment

on:
  push:
    tags:
      - v*.*.*

defaults:
  run:
    shell: bash

jobs:
  library-deployment:
    name: Build and upload provider
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@master
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.1.0
        with:
          repo: pulumi/pulumictl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
          registry-url: https://registry.npmjs.org
      - name: Install yarn
        run: npm install --global yarn
      - name: Setup DotNet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Setup DotNet ICU
        run: sudo apt-get update && sudo apt-get install -y icu-devtools
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Print version
        run: pulumictl get version
      - name: Create .npmrc
        run: printf "@spacelift-io:registry=https://npm.pkg.github.com\n//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}\n" > sdk/nodejs/bin/.npmrc
      - name: Publish npm package.
        run: cd sdk/nodejs/bin && npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build dotnet package
        run: make build_dotnet
      - name: Package dotnet
        run: cd sdk/dotnet && dotnet pack --configuration Release /p:Version=$(git describe --tags --abbrev=0 | sed 's/^v//g')
      - name: Create NuGet config
        run: cp nuget.config.template sdk/dotnet/nuget.config
      - name: Publish dotnet package
        run: cd sdk/dotnet && dotnet nuget push "bin/Release/Pulumi.Spacelift.$(git describe --tags --abbrev=0 | sed 's/^v//g').nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
