name: Preprod deployment

on: [push]

jobs:
  preprod-provider-deployment:
    name: Build and upload provider
    runs-on: ubuntu-latest
    container: golang:1.15-alpine
    steps:
      - name: Install build dependencies
        run: |
          apk add --no-cache alpine-sdk git python3 py3-pip
          pip3 install --upgrade pip
          pip3 install awscli

      - name: Check out repository code
        uses: actions/checkout@master

      - name: Remove Pulumi directory
        run: rm -rf /github/home/.pulumi

      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.1.0
        with:
          repo: pulumi/pulumictl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1.0.1

      - name: Tag version
        run: git tag -d `git tag | grep -E '.'` && git tag v0.0.0

      - name: Print version
        run: pulumictl get version

      - name: Build provider
        run: make provider
        env:
          PROVIDER_OS: ${{ matrix.provider_os }}

      - name: Create package directory
        run: mkdir package && mv bin/pulumi-resource-* package/ && ls -la package/

      - name: Create package
        run: cd package && tar -zcvf pulumi-resource-spacelift-v0.0.0-${{matrix.provider_os}}-amd64.tar.gz pulumi-resource-*

      - name: Create upload directory
        run: mkdir -p upload/pulumi-plugins && mv package/*.tar.gz upload/pulumi-plugins/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.5.8
        with:
          aws-region: ${{ secrets.PREPROD_AWS_REGION }}
          aws-access-key-id: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}

      - name: Upload the provider binary to downloads.spacelift.dev (dry run)
        if: github.ref != 'refs/heads/future'
        run: >-
          aws s3 sync
          upload/ s3://${{ secrets.PREPROD_AWS_S3_BUCKET }}/
          --dryrun
          --no-progress

      - name: Upload the provider binary to downloads.spacelift.dev
        if: github.ref == 'refs/heads/future'
        run: >-
          aws s3 sync
          upload/ s3://${{ secrets.PREPROD_AWS_S3_BUCKET }}/
          --no-progress

      - name: Invalidate downloads.spacelift.dev cache
        if: github.ref == 'refs/heads/future'
        run: >-
          aws cloudfront create-invalidation
          --distribution-id ${{ secrets.PREPROD_DISTRIBUTION }}
          --paths "/*"

    strategy:
      matrix:
        provider_os:
          - darwin
          - linux
          - windows
