// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * `spacelift.VcsAgentPool` represents a Spacelift **VCS agent pool** - a logical group of proxies allowing Spacelift to access private VCS installations
 */
export function getVcsAgentPool(args: GetVcsAgentPoolArgs, opts?: pulumi.InvokeOptions): Promise<GetVcsAgentPoolResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("spacelift:index/getVcsAgentPool:getVcsAgentPool", {
        "vcsAgentPoolId": args.vcsAgentPoolId,
    }, opts);
}

/**
 * A collection of arguments for invoking getVcsAgentPool.
 */
export interface GetVcsAgentPoolArgs {
    /**
     * ID of the VCS agent pool to retrieve
     */
    vcsAgentPoolId: string;
}

/**
 * A collection of values returned by getVcsAgentPool.
 */
export interface GetVcsAgentPoolResult {
    /**
     * Free-form VCS agent pool description for users
     */
    readonly description: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Name of the VCS agent pool
     */
    readonly name: string;
    /**
     * ID of the VCS agent pool to retrieve
     */
    readonly vcsAgentPoolId: string;
}
/**
 * `spacelift.VcsAgentPool` represents a Spacelift **VCS agent pool** - a logical group of proxies allowing Spacelift to access private VCS installations
 */
export function getVcsAgentPoolOutput(args: GetVcsAgentPoolOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetVcsAgentPoolResult> {
    return pulumi.output(args).apply((a: any) => getVcsAgentPool(a, opts))
}

/**
 * A collection of arguments for invoking getVcsAgentPool.
 */
export interface GetVcsAgentPoolOutputArgs {
    /**
     * ID of the VCS agent pool to retrieve
     */
    vcsAgentPoolId: pulumi.Input<string>;
}
