// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * `spacelift.ScheduledDeleteTask` represents a scheduling configuration for a Stack. It will trigger a stack deletion task at the given timestamp.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as spacelift from "@spacelift-io/pulumi-spacelift";
 *
 * const k8s_core = new spacelift.Stack("k8s-core", {});
 * // at a given timestamp (unix)
 * const k8s_core_delete = new spacelift.ScheduledDeleteTask("k8s-core-delete", {
 *     stackId: k8s_core.id,
 *     at: 1663336895,
 *     deleteResources: true,
 * });
 * ```
 *
 * ## Import
 *
 * ```sh
 * $ pulumi import spacelift:index/scheduledDeleteTask:ScheduledDeleteTask ireland-kubeconfig $STACK_ID/$SCHEDULED_DELETE_STACK_ID
 * ```
 */
export class ScheduledDeleteTask extends pulumi.CustomResource {
    /**
     * Get an existing ScheduledDeleteTask resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ScheduledDeleteTaskState, opts?: pulumi.CustomResourceOptions): ScheduledDeleteTask {
        return new ScheduledDeleteTask(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'spacelift:index/scheduledDeleteTask:ScheduledDeleteTask';

    /**
     * Returns true if the given object is an instance of ScheduledDeleteTask.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ScheduledDeleteTask {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ScheduledDeleteTask.__pulumiType;
    }

    /**
     * Timestamp (unix timestamp) at which time the scheduling should happen.
     */
    declare public readonly at: pulumi.Output<number>;
    /**
     * Indicates whether the resources of the stack should be deleted.
     */
    declare public readonly deleteResources: pulumi.Output<boolean | undefined>;
    /**
     * ID of the schedule
     */
    declare public readonly scheduleId: pulumi.Output<string>;
    /**
     * ID of the stack for which to set up scheduling
     */
    declare public readonly stackId: pulumi.Output<string>;

    /**
     * Create a ScheduledDeleteTask resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ScheduledDeleteTaskArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ScheduledDeleteTaskArgs | ScheduledDeleteTaskState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ScheduledDeleteTaskState | undefined;
            resourceInputs["at"] = state?.at;
            resourceInputs["deleteResources"] = state?.deleteResources;
            resourceInputs["scheduleId"] = state?.scheduleId;
            resourceInputs["stackId"] = state?.stackId;
        } else {
            const args = argsOrState as ScheduledDeleteTaskArgs | undefined;
            if (args?.at === undefined && !opts.urn) {
                throw new Error("Missing required property 'at'");
            }
            if (args?.stackId === undefined && !opts.urn) {
                throw new Error("Missing required property 'stackId'");
            }
            resourceInputs["at"] = args?.at;
            resourceInputs["deleteResources"] = args?.deleteResources;
            resourceInputs["scheduleId"] = args?.scheduleId;
            resourceInputs["stackId"] = args?.stackId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ScheduledDeleteTask.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ScheduledDeleteTask resources.
 */
export interface ScheduledDeleteTaskState {
    /**
     * Timestamp (unix timestamp) at which time the scheduling should happen.
     */
    at?: pulumi.Input<number>;
    /**
     * Indicates whether the resources of the stack should be deleted.
     */
    deleteResources?: pulumi.Input<boolean>;
    /**
     * ID of the schedule
     */
    scheduleId?: pulumi.Input<string>;
    /**
     * ID of the stack for which to set up scheduling
     */
    stackId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ScheduledDeleteTask resource.
 */
export interface ScheduledDeleteTaskArgs {
    /**
     * Timestamp (unix timestamp) at which time the scheduling should happen.
     */
    at: pulumi.Input<number>;
    /**
     * Indicates whether the resources of the stack should be deleted.
     */
    deleteResources?: pulumi.Input<boolean>;
    /**
     * ID of the schedule
     */
    scheduleId?: pulumi.Input<string>;
    /**
     * ID of the stack for which to set up scheduling
     */
    stackId: pulumi.Input<string>;
}
