// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class WorkerPool extends pulumi.CustomResource {
    /**
     * Get an existing WorkerPool resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: WorkerPoolState, opts?: pulumi.CustomResourceOptions): WorkerPool {
        return new WorkerPool(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'spacelift:index/workerPool:WorkerPool';

    /**
     * Returns true if the given object is an instance of WorkerPool.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is WorkerPool {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WorkerPool.__pulumiType;
    }

    /**
     * credentials necessary to connect WorkerPool's workers to the control plane
     */
    public /*out*/ readonly config!: pulumi.Output<string>;
    /**
     * certificate signing request in base64
     */
    public readonly csr!: pulumi.Output<string>;
    /**
     * description of the worker pool
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * name of the worker pool
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * private key in base64
     */
    public /*out*/ readonly privateKey!: pulumi.Output<string>;

    /**
     * Create a WorkerPool resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WorkerPoolArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: WorkerPoolArgs | WorkerPoolState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as WorkerPoolState | undefined;
            inputs["config"] = state ? state.config : undefined;
            inputs["csr"] = state ? state.csr : undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["privateKey"] = state ? state.privateKey : undefined;
        } else {
            const args = argsOrState as WorkerPoolArgs | undefined;
            if ((!args || args.name === undefined) && !(opts && opts.urn)) {
                throw new Error("Missing required property 'name'");
            }
            inputs["csr"] = args ? args.csr : undefined;
            inputs["description"] = args ? args.description : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["config"] = undefined /*out*/;
            inputs["privateKey"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(WorkerPool.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering WorkerPool resources.
 */
export interface WorkerPoolState {
    /**
     * credentials necessary to connect WorkerPool's workers to the control plane
     */
    readonly config?: pulumi.Input<string>;
    /**
     * certificate signing request in base64
     */
    readonly csr?: pulumi.Input<string>;
    /**
     * description of the worker pool
     */
    readonly description?: pulumi.Input<string>;
    /**
     * name of the worker pool
     */
    readonly name?: pulumi.Input<string>;
    /**
     * private key in base64
     */
    readonly privateKey?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a WorkerPool resource.
 */
export interface WorkerPoolArgs {
    /**
     * certificate signing request in base64
     */
    readonly csr?: pulumi.Input<string>;
    /**
     * description of the worker pool
     */
    readonly description?: pulumi.Input<string>;
    /**
     * name of the worker pool
     */
    readonly name: pulumi.Input<string>;
}
